### ISSUE TITLE
Deploying gdamjan.uwsgi on ubuntu 14:04 gives webdav error "fatal error: attr/xattr.h: No such file or directory"

### ISSUE THREAD

**Issue by joshua-atkins** [gdamjan/ansible-uwsgi#5]
# Problem/Scenario
Original `site.yml` is as follows:
```yml
---
- name: Install uwsgi
  hosts: web-servers
  roles:
   - role: gdamjan.uwsgi
```
which was running on a clean ubuntu:14.04 docker container.

Produced the following error during
`TASK: [gdamjan.uwsgi | Building other uwsgi plugins] **************************`

```
failed: [localhost] => (item=webdav) => {"changed": true, "cmd": "python uwsgiconfig.py --plugin plugins/webdav uwsgibuild webdav", "delta": "0:00:00.824577", "end": "2015-06-02 22:21:56.091311", "item": "webdav", "rc": 1, "start": "2015-06-02 22:21:55.266734", "warnings": []}
stderr: plugins/webdav/webdav.c:6:24: fatal error: attr/xattr.h: No such file or directory
 #include <attr/xattr.h>
                        ^
compilation terminated.
stdout: using profile: buildconf/uwsgibuild.ini
detected include path: ['/usr/lib/gcc/x86_64-linux-gnu/4.8/include', '/usr/local/include', '/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed', '/usr/include/x86_64-linux-gnu', '/usr/include']
*** uWSGI building and linking plugin plugins/webdav ***
[x86_64-linux-gnu-gcc -pthread] ./webdav_plugin.so
*** unable to build webdav plugin ***
```

For completeness, hosts defined as:
```
[local]
localhost

[web-servers:children]
local
```

# Quick fix
Error didn't appear when changing `site.yml` to the following:
```yml
---
# Run the installation for libattr1-dev before running the gdamjan.uwsgi role
- name: Sandbox
  hosts: web-servers
  tasks:
   - name: install libattr1-dev
     shell: apt-get -y install libattr1-dev

# Carry on as before
- name: Install uwsgi
  hosts: web-servers
  roles:
   - role: gdamjan.uwsgi
```
# Proposed solution
It does not look like `libattr1-dev` is present in `ansible-uwsgi/tasks/packages.yml`, and so should perhaps be added to `with_items` in the section named `Making sure uwsgi dependencies are installed from apt...`

## Comment
I've not submitted an issue before, apologies if I've not done it in the right way!
